apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tcs-agentic-ai
  namespace: openshift-tcs-agentic
  labels:
    app: tcs-agentic-ai
spec:
  to:
    kind: Service
    name: tcs-agentic-ai
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
