apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcp-server-data
  namespace: openshift-mcp
  labels:
    app.kubernetes.io/name: openshift-mcp-server
    app.kubernetes.io/part-of: mcp-ai-assistant
spec:
  storageClassName: vxflexos-xfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
